# -*- coding: utf-8 -*-
"""RESUME_AI4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dT_0UKS1TR7pFkYnFHukPfM9ZBxaeXLU
"""

!pip install pdfplumber python-docx sentence-transformers scikit-learn pandas matplotlib

from google.colab import files
uploaded = files.upload()

# Define the job description
job_description = """
We are hiring a Computer Science with strong skills in Python, Machine Learning, Cloud Computing, SQL and NLP.
Experience with TensorFlow, PyTorch, PHP , Machine Learning and cloud platforms is preferred.
"""

import pdfplumber
import docx

def extract_text_from_pdf(pdf_path):
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            if page.extract_text():
                text += page.extract_text() + " "
    return text

def extract_text_from_docx(docx_path):
    doc = docx.Document(docx_path)
    return " ".join([para.text for para in doc.paragraphs])

resume_texts = []
resume_names = []

for filename in uploaded.keys():
    if filename.endswith(".pdf"):
        resume_texts.append(extract_text_from_pdf(filename))
        resume_names.append(filename)
    elif filename.endswith(".docx"):
        resume_texts.append(extract_text_from_docx(filename))
        resume_names.append(filename)

#import numpy as np
#from sentence_transformers import SentenceTransformer
#Initialize the sentence transformer model
#model = SentenceTransformer
#resume_embeddings = np.array(model.encode(resume_texts))
#jd_embedding = np.array(model.encode([job_description]))[0]
#resume_embeddings = model.encode(resume_texts, batch_size=8, show_progress_bar=True)
#jd_embedding = model.encode([job_description], batch_size=8)[0]------------------------------------


from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

#resume_embeddings = model.encode(resume_texts, convert_to_tensor=True)
#jd_embedding = model.encode(job_description, convert_to_tensor=True)----------------------------------------


resume_embeddings = model.encode(resume_texts, normalize_embeddings=True)
jd_embedding = model.encode([job_description], normalize_embeddings=True)[0]

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

similarities = cosine_similarity(resume_embeddings, [jd_embedding])
scores = (similarities.flatten() * 100).round(-1)
ranking = np.argsort(scores)[::-1]

import pandas as pd

results = pd.DataFrame({
    'Resume': resume_names,
    'Match Score (0-100)': scores
}).sort_values(by='Match Score (0-100)', ascending=False)

results

import matplotlib.pyplot as plt
results.plot(y='Match Score (0-100)', kind='bar', figsize=(10,5), color='skyblue')
plt.title("Resume Match Scores")
plt.xlabel("Resume")
plt.show()

required_skills = ["Python", "Machine Learning", "NLP", "TensorFlow", "PyTorch", "Cloud", "JAVA", "PHP", "SQL", "GRAPHIC DESIGNer", "C", "DBMs"]

from rich import print
def skill_gap(resume_text, skills):
    missing = [skill for skill in skills if skill.lower() not in resume_text.lower()]
    return missing

for i, text in enumerate(resume_texts):
    print(f"Resume:   [bold]{resume_names[i]}[/bold]\n\n")
    print("Missing Skills:  ",skill_gap(text, required_skills))
    print("-"*50)

required_skills = ["Python", "Machine Learning", "NLP", "TensorFlow", "PyTorch", "Cloud", "GRAPHIC DESIGNer", "C", "DBMS"]

def skill_analysis(resume_text, skills):
    matched = [skill for skill in skills if skill.lower() in resume_text.lower()]
    missing = [skill for skill in skills if skill.lower() not in resume_text.lower()]
    return matched, missing

for i, text in enumerate(resume_texts):
    matched, missing = skill_analysis(text, required_skills)
    print(f"Resume:  [bold]{list(uploaded.keys())[i]}[/bold]\n\n")
    print("Matched Skills:  ", " | ".join(matched))
    print("\n\nMissing Skills:  ", " | ".join(missing))
    print("-"*50)

import pdfplumber, docx

def extract_text(filename):
    if filename.endswith(".pdf"):
        with pdfplumber.open(filename) as pdf:
            return "\n".join([p.extract_text() for p in pdf.pages if p.extract_text()])
    elif filename.endswith(".docx"):
        return "\n".join([p.text for p in docx.Document(filename).paragraphs])
    return ""

for fname in uploaded.keys():
    text = extract_text(fname)
    print(f"\n=== Resume Content from {fname} ===\n")
    print(text[:2000])